### ISSUE TITLE
Application fast closes when network connection change.

### ISSUE THREAD

**Issue by FDT-Dirk** [Ashfaaq18/OpenNetMeter#58] opened 2022-07-14 06:42 UTC
Hi,

the application fast closes/crashes when the network connection change.
I already had the impression since an earlier version, but I thought it is due to my last bug report with the freezing display, so I didn't mention it in my last report to not mix up issues. But it stays to be the same even in version 12.
I notice this behavior when I enter/exit my vpn connection (need to use vpn often).

Kind regards
Dirk

**Comment by Ashfaaq18** [comment] 2022-07-14 07:40
Hi @FDT-Dirk, thanks for reporting the problem.

could you list the steps to reproduce this bug?

**Comment by FDT-Dirk** [comment] 2022-07-14 07:44
Hi,

for me it happens when I turn on/off the vpn connection.
The app is not able to handle the "new" way of standard communication of the device (laptop;Win10pro) and crashes.

Kind regards
Dirk

**Comment by Ashfaaq18** [comment] 2022-07-14 13:18
btw was this working fine before version 0.11.0? (version 0.10.0 or below)

when i switch connections from ethernet to wifi or wifi to ethernet, it switches without an issue. I'm suspecting this to be specific to VPN connections.

**Comment by FDT-Dirk** [comment] 2022-07-14 13:35
Hi,
I had it definitely in 11, if it happened in 10 I'm not sure.

Possible that it is something related to VPN, I said I'm not sure about the change WLAN to LAN.
I need to use VPN and there it happens.

**Comment by GenDrive-Dev** [comment] 2022-07-20 03:12
Hi there,

great application. Unfortunately I stumbled across the same problem, V0.12.0 seems to contain still the bug that the
application is crashing.

I post msg from windows log, maybe it will help to locate the problem:

Application: OpenNetMeter.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
   at OpenNetMeter.Models.ApplicationDB.GetID_DateTable(DateTime time)
   at OpenNetMeter.ViewModels.MainWindowVM.UpdateData()
   at OpenNetMeter.ViewModels.MainWindowVM.NetProc_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at OpenNetMeter.Models.NetworkProcess.EndNetworkProcess()
   at OpenNetMeter.Models.NetworkProcess.NetworkChange_NetworkAddressChanged(Object sender, EventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback(Object stateObject, Boolean signaled)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, Boolean timedOut)

**Comment by Ashfaaq18** [comment] 2022-07-20 09:49
Hi @GenDrive-Dev Thank you for the logs. From the looks of it though it does not seem to be related to the same issue here. Nevertheless, I'll still try fixing the error shown in your logs and let you know.

**Comment by FDT-Dirk** [comment] 2022-07-20 14:11
Hi @Ashfaaq18 ,
I checked my eventlogs too. I have the same failures like @GenDrive-Dev. Maybe my guess about entering/leaving the VPN was just an impression and might not be the real reason.
I'm looking forward for an corrected version, maybe the entries in the log and the according fix will also sort out my issues.
Kind regards
Dirk

**Comment by Ashfaaq18** [comment] 2022-07-20 18:12
@FDT-Dirk and @GenDrive-Dev , [here](https://github.com/Ashfaaq18/OpenNetMeter/releases/tag/v0.12.1) is a test version of the app with a fix for this issue. Let me know if its working. If its not, you could try pasting the error windows logs back again here. It will help me debug this.

**Comment by GenDrive-Dev** [comment] 2022-07-20 23:31
thank you for your fast response,
downloaded and activated on a very busy machine, I will report in 2 days if the problem is gone.

the 0.12.0 today crashed again and it seems it crash every day once, lets hope the problem is fixed now.

Even with the bug its a great application - rather before I use something else I prefer to use opennetmeter ;)

**Comment by Ashfaaq18** [comment] 2022-07-21 03:52
> Even with the bug its a great application - rather before I use something else I prefer to use opennetmeter ;)

Thank you.

**Comment by FDT-Dirk** [comment] 2022-07-21 06:23
Hi,
I turned on my computer this morning (from hibernate) saw your mail and that the tool was anyway gone, so I downloaded and installed the RC version. I started it and after that went in my necessary VPN session. Thats all about 20-25 min. in the past. Now the tool is still alive, but I have no longer any measured data shown by the tool. Neither in the widget nor in the summary when I open the tool itself. All values are zero, but tool reacts. I checked the error protocols, nothing in there after I installed&started the new version.
Kind regards
Dirk

**Comment by GenDrive-Dev** [comment] 2022-07-24 10:21
just a followup: the RC version so far is running for 3,5 days without any crash  - seems the bug is fixed

good job, Ashfaaq!

**Comment by Ashfaaq18** [comment] 2022-07-24 12:07
> just a followup: the RC version so far is running for 3,5 days without any crash - seems the bug is fixed
> 
> good job, Ashfaaq!

Thank you for the update

**Comment by FDT-Dirk** [comment] 2022-07-25 10:26
> 

Hi,
same on my PC, beside the first initial freeze of the shown values shortly after start of the rc version. Since then all is fine on my PC too.

Kind regards
Dirk

**Comment by Ashfaaq18** [comment] 2022-07-25 10:50
> > 
> 
> Hi, same on my PC, beside the first initial freeze of the shown values shortly after start of the rc version. Since then all is fine on my PC too.
> 
> Kind regards Dirk

Thank you for the update

**Comment by FDT-Dirk** [comment] 2022-07-27 14:25
Hi,
just to let you know. I had a no longer updating widget with the 12.1rc middle of the day (nothing to do with VPN; I suppose that's out now as possible reason). When I tried to open the try icon I got a black rectangle with nothing in it, just the frame around and all black inside. Nothing in system events.
Kind regards
Dirk

**Comment by FDT-Dirk** [comment] 2022-08-01 12:08
Hi,

had some minutes ago a crash of 12.1 in kernelbase.dll. It happened suddenly no idea with what it can be related.

Kind regards
Dirk

**Comment by Ashfaaq18** [comment] 2022-08-03 13:45
Hey @FDT-Dirk, 
Thanks for reporting. It would be great if you could open a new issue regarding this crash. I'll close this one since we've solved this. 
If you do encounter it again, you can log your findings to the new issue thread.

**Closed** 2022-08-31 05:42 UTC
